output_curency = "EUR"
[exchange_rate]
HUF = 402.80
RON = 5.03

[years_to_invest]
years = 5
[yearly_interest_rate]
EUR = 1.35
RON = 5.2
HUF = 6.5

[start_sum]
EUR = 10_000
RON = 50_000
HUF = 4_000_000
[yearly_investment]
EUR = 10_000


[settings]
displayed_decimal_length = 2