[output_curency]
EUR = 1
[exchange_rate]
HUF = 402.80
RON = 5.03

[years_to_invest]
years = 5
[yearly_interest_rate]
RON = 5.20
HUF = 6.50
EUR = 1.35

[start_sum]
EUR = 10_000
RON = 50_000
HUF = 4_000_000
[yearly_investment]
EUR = 10_000
