output_currency = "EUR"
[exchange_rate]
USD = 1.15
GBP = 0.85


[years_to_invest]
years = 5
[yearly_interest_rate]
EUR = 2.509
USD = 4.393
GBP = 4.532

[start_sum]
EUR = 12_000
USD = 9_500
GBP = 14_300
[yearly_investment]
EUR = 1_200
GBP = 6_000

[settings]
displayed_decimal_length = 2
digit_grouping_separator = ","
tab_size = 4
