output_currency = "EUR"
[exchange_rate]
HUF = 402.80
RON = 5.03

[years_to_invest]
years = 20
[yearly_interest_rate]
EUR = 1.35
RON = 5.2
HUF = 6.5

[start_sum]
EUR = 100
RON = 500
HUF = 40_000
[yearly_investment]
EUR = 100


[settings]
displayed_decimal_length = 2