output_currency = "EUR"   # currency you want to see as total at the end
[exchange_rate]
RON = 5.09
HUF = 391
# USD = 1.15                # exchange rates to the output currency

[years_to_invest]         # number of years to invest
years = 3
[yearly_interest_rate]    # interest rate per currency
HUF = 6.50
RON = 6.75
# EUR = 7

[start_sum]               # initial start sum per currency
HUF = 35_000_000
RON = 500_000
# EUR = 100_000
[yearly_investment]       # additional sum that will be added at the end each investment year
HUF = 8_000_000
# RON = 10_000

[settings]                # visual settings (don't change)
displayed_decimal_length = 2
digit_grouping_separator = ","
tab_size = 4
